<?php

namespace App\Filament\Resources;

use Filament\Forms;
use App\Models\Dh03;
use Filament\Tables;
use Filament\Forms\Form;
use Filament\Tables\Table;
use Filament\Resources\Resource;
use Filament\Tables\Filters\Filter;
use Filament\Tables\Columns\IconColumn;
use Filament\Tables\Columns\TextColumn;
use Illuminate\Database\Eloquent\Builder;
use App\Filament\Resources\Dh03Resource\Pages;
use Illuminate\Database\Eloquent\SoftDeletingScope;
use App\Filament\Resources\Dh03Resource\RelationManagers;

class Dh03Resource extends Resource
{
    protected static ?string $model = Dh03::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('rama')
                    ->maxLength(4),
                Forms\Components\TextInput::make('disciplina')
                    ->maxLength(4),
                Forms\Components\TextInput::make('area')
                    ->maxLength(4),
                Forms\Components\TextInput::make('porcdedicdocente')
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('porcdedicinvestig')
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('porcdedicagestion')
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('porcdedicaextens')
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('codigocontrato')
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('horassemanales')
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('duracioncontrato')
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('incisoimputacion')
                    ->maxLength(5),
                Forms\Components\TextInput::make('montocontrato')
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('nro_legaj')
                    ->numeric(),
                Forms\Components\DatePicker::make('fec_alta'),
                Forms\Components\DatePicker::make('fec_baja'),
                Forms\Components\TextInput::make('codc_carac')
                    ->maxLength(4),
                Forms\Components\TextInput::make('codc_categ')
                    ->maxLength(4),
                Forms\Components\TextInput::make('codc_agrup')
                    ->maxLength(4),
                Forms\Components\TextInput::make('tipo_norma')
                    ->maxLength(20),
                Forms\Components\TextInput::make('tipo_emite')
                    ->maxLength(20),
                Forms\Components\DatePicker::make('fec_norma'),
                Forms\Components\TextInput::make('nro_norma')
                    ->numeric(),
                Forms\Components\TextInput::make('codc_secex')
                    ->maxLength(4),
                Forms\Components\TextInput::make('nro_exped')
                    ->maxLength(20),
                Forms\Components\TextInput::make('nro_exped_baja')
                    ->maxLength(20),
                Forms\Components\DatePicker::make('fec_exped_baja'),
                Forms\Components\TextInput::make('ano_exped_baja')
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('codc_secex_baja')
                    ->maxLength(4),
                Forms\Components\TextInput::make('ano_exped')
                    ->numeric()
                    ->default(0),
                Forms\Components\DatePicker::make('fec_exped'),
                Forms\Components\TextInput::make('nro_tab13')
                    ->numeric()
                    ->default(13),
                Forms\Components\TextInput::make('codc_uacad')
                    ->maxLength(4),
                Forms\Components\TextInput::make('nro_tab18')
                    ->numeric()
                    ->default(18),
                Forms\Components\TextInput::make('codc_regio')
                    ->maxLength(4),
                Forms\Components\TextInput::make('codc_grado')
                    ->maxLength(4),
                Forms\Components\TextInput::make('vig_caano')
                    ->numeric(),
                Forms\Components\TextInput::make('vig_cames')
                    ->numeric(),
                Forms\Components\Toggle::make('chk_proye')
                    ->required(),
                Forms\Components\TextInput::make('tipo_incen')
                    ->maxLength(1),
                Forms\Components\TextInput::make('dedi_incen')
                    ->maxLength(4),
                Forms\Components\TextInput::make('cic_con')
                    ->maxLength(3),
                Forms\Components\DatePicker::make('fec_limite'),
                Forms\Components\TextInput::make('porc_aplic')
                    ->numeric(),
                Forms\Components\TextInput::make('hs_dedic')
                    ->numeric(),
                Forms\Components\TextInput::make('tipo_norma_baja')
                    ->maxLength(20),
                Forms\Components\TextInput::make('tipoemitenormabaja')
                    ->maxLength(20),
                Forms\Components\DatePicker::make('fecha_norma_baja'),
                Forms\Components\DatePicker::make('fechanotificacion'),
                Forms\Components\TextInput::make('coddependesemp')
                    ->maxLength(4),
                Forms\Components\TextInput::make('chkfirmaencargado')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('chkfirmaautoridad')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('chkestadoafip')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('chkestadotitulo')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('chkestadocv')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('objetocontrato')
                    ->maxLength(30),
                Forms\Components\TextInput::make('nro_norma_baja')
                    ->numeric()
                    ->default(0),
                Forms\Components\DatePicker::make('fechagrado'),
                Forms\Components\DatePicker::make('fechapermanencia'),
                Forms\Components\DatePicker::make('fecaltadesig'),
                Forms\Components\DatePicker::make('fecbajadesig'),
                Forms\Components\TextInput::make('motivoaltadesig')
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('motivobajadesig')
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('renovacion')
                    ->maxLength(20),
                Forms\Components\TextInput::make('idtareacargo')
                    ->numeric(),
                Forms\Components\Toggle::make('chktrayectoria')
                    ->required(),
                Forms\Components\Toggle::make('chkfuncionejec')
                    ->required(),
                Forms\Components\Toggle::make('chkretroactivo')
                    ->required(),
                Forms\Components\TextInput::make('chkstopliq')
                    ->required()
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('nro_cargo_ant')
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('transito')
                    ->numeric()
                    ->default(0),
                Forms\Components\TextInput::make('cod_clasif_cargo')
                    ->numeric(),
                Forms\Components\TextInput::make('cod_licencia')
                    ->numeric(),
                Forms\Components\Toggle::make('cargo_concursado')
                    ->required(),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('nro_cargo')
                    ->searchable()
                    ->numeric()
                    ->sortable(),
                TextColumn::make('nro_legaj')
                    ->numeric()
                    ->sortable()
                    ->searchable(),
                TextColumn::make('dh01.nro_cuil')
                    ->label('DNI')
                    ->searchable(),
                TextColumn::make('dh01.desc_appat')
                    ->label('Apellido Paterno')
                    ->searchable(),
                TextColumn::make('dh01.desc_nombr')
                    ->label('Nombre')
                    ->searchable(),
                TextColumn::make('rama')
                    ->toggleable()
                    ,
                TextColumn::make('disciplina')
                    ->toggleable()
                    ,
                TextColumn::make('area')
                    ->toggleable()
                    ,
                TextColumn::make('porcdedicdocente')
                    ->toggleable()
                    ->numeric()
                    ->sortable(),
                TextColumn::make('porcdedicinvestig')
                    ->toggleable()
                    ->numeric()
                    ->sortable(),
                TextColumn::make('porcdedicagestion')->toggleable()
                    ->numeric()
                    ->sortable(),
                TextColumn::make('porcdedicaextens')->toggleable()
                    ->numeric()
                    ->sortable(),
                TextColumn::make('codigocontrato')->toggleable()
                    ->numeric()
                    ->sortable(),
                TextColumn::make('horassemanales')->toggleable()
                    ->numeric()
                    ->sortable(),
                TextColumn::make('duracioncontrato')->toggleable()
                    ->numeric()
                    ->sortable(),
                TextColumn::make('incisoimputacion')->toggleable()
                    ,
                TextColumn::make('montocontrato')
                    ->toggleable()
                    ->numeric()
                    ->sortable(),
                TextColumn::make('fec_alta')
                    ->date()
                    ->sortable(),
                TextColumn::make('fec_baja')
                    ->date()
                    ->sortable(),
                TextColumn::make('codc_carac')->toggleable()
                    ,
                TextColumn::make('codc_categ')
                    ,
                TextColumn::make('codc_agrup')
                    ,
                TextColumn::make('tipo_norma')->toggleable()
                    ,
                TextColumn::make('tipo_emite')->toggleable()
                    ,
                TextColumn::make('fec_norma')->toggleable()
                    ->date()
                    ->sortable(),
                TextColumn::make('nro_norma')->toggleable()
                    ->numeric()
                    ->sortable(),
                TextColumn::make('codc_secex')->toggleable()
                    ,
                TextColumn::make('nro_exped')->toggleable()
                    ,
                TextColumn::make('nro_exped_baja')->toggleable()
                    ,
                TextColumn::make('fec_exped_baja')->toggleable()
                    ->date()
                    ->sortable(),
                TextColumn::make('ano_exped_baja')->toggleable()
                    ->numeric()
                    ->sortable(),
                TextColumn::make('codc_secex_baja')->toggleable()
                    ,
                TextColumn::make('ano_exped')->toggleable()
                    ->numeric()
                    ->sortable(),
                TextColumn::make('fec_exped')->toggleable()
                    ->date()
                    ->sortable(),
                TextColumn::make('nro_tab13')->toggleable()
                    ->numeric()
                    ->sortable(),
                TextColumn::make('codc_uacad')
                    ,
                TextColumn::make('nro_tab18')->toggleable()
                    ->numeric()
                    ->sortable(),
                TextColumn::make('codc_regio')->toggleable()
                    ,
                TextColumn::make('codc_grado')->toggleable()
                    ,
                TextColumn::make('vig_caano')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('vig_cames')
                    ->numeric()
                    ->sortable(),
                IconColumn::make('chk_proye')
                    ->boolean(),
                TextColumn::make('tipo_incen')
                    ,
                TextColumn::make('dedi_incen')
                    ,
                TextColumn::make('cic_con')
                    ,
                TextColumn::make('fec_limite')
                    ->date()
                    ->sortable(),
                TextColumn::make('porc_aplic')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('hs_dedic')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('tipo_norma_baja')
                    ,
                TextColumn::make('tipoemitenormabaja')
                    ,
                TextColumn::make('fecha_norma_baja')
                    ->date()
                    ->sortable(),
                TextColumn::make('fechanotificacion')
                    ->date()
                    ->sortable(),
                TextColumn::make('coddependesemp')
                    ,
                TextColumn::make('chkfirmaencargado')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('chkfirmaautoridad')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('chkestadoafip')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('chkestadotitulo')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('chkestadocv')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('objetocontrato')
                    ,
                TextColumn::make('nro_norma_baja')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('fechagrado')
                    ->date()
                    ->sortable(),
                TextColumn::make('fechapermanencia')
                    ->date()
                    ->sortable(),
                TextColumn::make('fecaltadesig')
                    ->date()
                    ->sortable(),
                TextColumn::make('fecbajadesig')
                    ->date()
                    ->sortable(),
                TextColumn::make('motivoaltadesig')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('motivobajadesig')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('renovacion')
                    ,
                TextColumn::make('idtareacargo')
                    ->numeric()
                    ->sortable(),
                IconColumn::make('chktrayectoria')
                    ->boolean(),
                IconColumn::make('chkfuncionejec')
                    ->boolean(),
                IconColumn::make('chkretroactivo')
                    ->boolean(),
                IconColumn::make('chkstopliq')
                    ->boolean(),
                TextColumn::make('nro_cargo_ant')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('transito')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('cod_clasif_cargo')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('cod_licencia')
                    ->numeric()
                    ->sortable(),
                IconColumn::make('cargo_concursado')
                    ->boolean(),
            ])
            ->filters([
                Filter::make('chkstopliq')
                    ->label('Chkstopliq')
                    ->toggle()
                    ->query(fn ($query) => $query->where('chkstopliq', false))
                    ->default(true), // Aplicar el filtro por defecto
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ])
            ->defaultSort('nro_cargo', 'desc')
            ->paginated(5) //configurar la paginacion
            ->paginationPageOptions([5,10,25,50,100, 250, 500, 1000]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListDh03s::route('/'),
            'create' => Pages\CreateDh03::route('/create'),
            'edit' => Pages\EditDh03::route('/{record}/edit'),
        ];
    }
}
